name: Linklado
description: Linklado em Flutter
version: 1.1.0+3

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  win32: ^2.7.0
  window_manager: ^0.2.5
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  msix: ^3.6.2


flutter:
  uses-material-design: true

  assets:
    - assets/logo_linklado.png

msix_config:
  display_name: Linklado
  publisher_display_name: Juliano Portela
  publisher: CN=272D95AB-3D0C-4E95-9BFE-BD6AB3EADA59
  identity_name: 44341JulianoPortela.Linklado
  languages: pt-br
  logo_path: C:\Users\nerdp\Documents\FlutterProjects\tuklado_flutter\windows\runner\resources\app_icon.ico
  certificate_path: C:\Windows\System32\CERTIFICATE2.pfx
  certificate_password: numero0365
